version: '3.7'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        CONTAINER_GID: '${CONTAINER_GID:-1000}'
        CONTAINER_UID: '${CONTAINER_UID:-1000}'
    restart: unless-stopped
    command: bundle exec puma
    user: $CONTAINER_UID:$CONTAINER_GID
    env_file: .env
    volumes:
      - ./:/opt/
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "-o", "/dev/null", "http://127.0.0.1:3000/ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    ports:
      - 3000:3000

  database:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 30
